/*
 * 대화 전용 이탈리아어 → 한글 단어 사전
 * 대화(dialogue)·질문·예문에 등장하는 단어의 뜻을 보여주기 위한 사전입니다.
 * 발음(reading)은 pronounce.ts의 규칙 기반 변환기로 실시간 계산합니다.
 * 사전에 없는 단어(고유명사·의미 없는 축약 조각 등)는 자동으로 생략됩니다.
 */
import { esToHangul } from "./pronounce";

export const glossary: Record<string, string> = {
  "a": "~에/~에게",
  "adesso": "지금",
  "al": "~에(a+il)",
  "alle": "~에(a+le, 시각)",
  "allora": "그럼/그때",
  "altro": "다른",
  "alzo": "나는 일어난다(alzarsi)",
  "amica": "친구(여)",
  "amici": "친구들",
  "amico": "친구(남)",
  "anche": "~도/또한",
  "ancora": "아직/또",
  "andiamo": "우리 가자",
  "ansia": "불안",
  "arrivederci": "안녕히 가세요",
  "assomigliate": "너희는 닮았다",
  "assomiglio": "나는 닮았다",
  "avere": "가지다",
  "banco": "바 카운터",
  "bel": "좋은/멋진(남)",
  "bello": "멋진/좋은",
  "bene": "잘/좋아/좋은",
  "beve": "그/그녀는 마신다",
  "bevi": "너는 마신다",
  "bilanci": "균형/예산(들)",
  "bilancio": "균형",
  "buonanotte": "잘 자요",
  "buonasera": "좋은 저녁",
  "buone": "좋은(여복)",
  "buongiorno": "안녕하세요",
  "buonissimo": "아주 맛있는",
  "caffè": "커피",
  "caldo": "더운/더위",
  "cambiamento": "변화",
  "cambiano": "그들은 변한다",
  "cappuccino": "카푸치노",
  "carne": "고기",
  "casa": "집",
  "cena": "저녁식사",
  "ceno": "나는 저녁을 먹는다",
  "certo": "물론",
  "che": "~것/~라는/무엇",
  "chi": "누구",
  "chiami": "너는 ~라고 불린다",
  "chiamo": "나는 ~라고 불린다(이름이 ~다)",
  "ci": "우리를/거기",
  "ciao": "안녕(친근)",
  "cibo": "음식",
  "cinquanta": "오십",
  "cinque": "다섯",
  "climatico": "기후의",
  "colazione": "아침식사",
  "come": "어떻게/~처럼",
  "con": "~와 함께",
  "conoscere": "알다/만나다",
  "conosci": "너는 안다",
  "conta": "중요하다/세다",
  "conto": "계산서",
  "corea": "한국",
  "cornetto": "크루아상",
  "cosa": "무엇",
  "costa": "(값이) 든다",
  "costano": "(값이) 든다(복)",
  "cucina": "부엌/요리",
  "cucini": "너는 요리한다",
  "cultura": "문화",
  "da": "~로부터/~에게",
  "dal": "~로부터(da+il)",
  "dei": "~의(di+i)",
  "del": "~의(di+il)",
  "dell": "~의(축약)",
  "della": "~의(di+la)",
  "di": "~의/~로부터",
  "dici": "너는 말한다",
  "dicono": "그들은 말한다",
  "diversi": "여러/서로 다른",
  "domani": "내일",
  "dopo": "후에",
  "dove": "어디",
  "due": "둘",
  "e": "그리고",
  "ecco": "여기 있다/바로",
  "esco": "나는 나간다(uscire)",
  "essere": "이다/있다",
  "euro": "유로",
  "fa": "그/그녀는 한다/(날씨가) ~하다",
  "facciamo": "우리는 한다",
  "faccio": "나는 한다",
  "fai": "너는 한다",
  "fame": "배고픔",
  "famiglia": "가족",
  "fare": "하다/만들다",
  "favore": "부탁",
  "forma": "형태",
  "formali": "격식의",
  "fra": "~사이에",
  "fratelli": "형제들",
  "fratello": "남자형제",
  "freddo": "추운/추위",
  "fuori": "밖에",
  "genitori": "부모",
  "gente": "사람들/대중",
  "giacca": "재킷",
  "giornata": "하루",
  "giorni": "날들",
  "giorno": "날/낮",
  "già": "이미",
  "gli": "그(남성 복수 관사)",
  "grazie": "고마워요",
  "ha": "그/그녀는 가지고 있다",
  "hai": "너는 가지고 있다",
  "ho": "나는 가지고 있다",
  "i": "그(남성 복수 관사)",
  "ieri": "어제",
  "il": "그(남성 정관사)",
  "importante": "중요한",
  "impressione": "인상",
  "in": "~안에/~에",
  "incontri": "만남들/너는 만난다",
  "influisce": "영향을 준다",
  "informali": "비격식의",
  "insieme": "함께",
  "invece": "반대로/대신",
  "io": "나",
  "italia": "이탈리아",
  "italiana": "이탈리아의(여)",
  "l": "(관사 축약)",
  "la": "그(여성 정관사)",
  "lavoro": "일/직장",
  "le": "그(여성 복수 관사)",
  "lei": "그녀/당신(존대)",
  "lo": "그(남성 정관사)",
  "lunghi": "긴(남복)",
  "ma": "하지만",
  "madre": "어머니",
  "mai": "결코",
  "mangi": "너는 먹는다",
  "mangiamo": "우리는 먹는다",
  "mangiare": "먹다",
  "maniere": "매너/방식",
  "mattina": "아침",
  "me": "나",
  "meglio": "더 낫게",
  "meno": "덜",
  "menu": "메뉴",
  "menù": "메뉴",
  "metro": "지하철",
  "mette": "넣다/두다",
  "mi": "나를/나에게",
  "mia": "나의(여)",
  "miei": "나의(남복)",
  "min": "분(minuti 약자)",
  "mio": "나의(남)",
  "molto": "매우/많이",
  "momento": "순간",
  "nel": "~안에(in+il)",
  "nella": "~안에(in+la)",
  "nelle": "~안에(in+le)",
  "noi": "우리",
  "non": "~아니다(부정)",
  "notte": "밤",
  "nuova": "새로운(여)",
  "nuovo": "새로운(남)",
  "o": "또는",
  "oggi": "오늘",
  "ognuno": "각자",
  "ora": "지금/시간",
  "orari": "시간표",
  "orario": "시간표",
  "ottima": "훌륭한(여)",
  "ottimo": "훌륭한(남)",
  "otto": "여덟",
  "padre": "아버지",
  "pago": "나는 지불한다",
  "pane": "빵",
  "passeggiata": "산책",
  "pasta": "파스타/면",
  "pasti": "식사들",
  "pensi": "너는 생각한다",
  "per": "~위해/~당",
  "perché": "왜/왜냐하면",
  "perfetto": "완벽한",
  "persona": "사람",
  "persone": "사람들",
  "pesce": "생선",
  "piacciono": "마음에 든다(복수 주어)",
  "piace": "마음에 든다",
  "piacere": "반가워요/좋아하다",
  "piatto": "접시/요리",
  "piccola": "작은(여)",
  "piccolo": "작은(남)",
  "piedi": "발(a piedi 걸어서)",
  "pioggia": "비",
  "piove": "비가 온다",
  "pizza": "피자",
  "più": "더",
  "poco": "조금",
  "posso": "~할 수 있다(나)",
  "pranzo": "점심",
  "preferisci": "너는 선호한다",
  "preferita": "가장 좋아하는(여)",
  "preferito": "가장 좋아하는(남)",
  "prego": "천만에요/여기요",
  "prendi": "너는 택한다/주문한다",
  "prendo": "나는 택한다/주문한다",
  "presenti": "소개하다/참석한",
  "preso": "택한/주문한",
  "presto": "일찍/곧",
  "prima": "먼저/전에",
  "primo": "첫 번째",
  "qual": "어느/무엇",
  "quale": "어느",
  "quando": "언제",
  "quante": "몇 개(여)",
  "quanti": "몇 개(남)",
  "quanto": "얼마/얼마나",
  "quattro": "넷",
  "quello": "저것",
  "questa": "이것(여)",
  "questo": "이것(남)",
  "racconta": "이야기해 봐",
  "rilassa": "편하게 하다",
  "rilassati": "긴장 풀어",
  "ristorante": "식당",
  "roma": "로마",
  "routine": "일과",
  "saluti": "인사(들)",
  "salve": "안녕하세요(중립)",
  "scegli": "너는 고른다",
  "scelta": "선택",
  "scusa": "미안/실례(친근)",
  "scusi": "실례합니다(존대)",
  "se": "만약",
  "secondo": "두 번째/~에 따르면",
  "sei": "여섯/너는 ~이다",
  "sempre": "항상",
  "sera": "저녁",
  "sette": "일곱",
  "settimana": "주",
  "seul": "서울",
  "si": "자기/네(긍정)",
  "siamo": "우리는 ~이다",
  "siete": "너희는 ~이다",
  "significa": "의미한다",
  "signora": "부인/여사님",
  "signore": "신사/선생님",
  "solito": "평소의",
  "solo": "오직/혼자",
  "sono": "나는 ~이다/그들은 ~이다",
  "sorella": "여자형제",
  "sorelle": "자매들",
  "spaghetti": "스파게티",
  "spesso": "자주",
  "sta": "있다/지내다(stare)",
  "stagione": "계절",
  "stai": "잘 지내?(stare)",
  "studente": "학생",
  "su": "~위에",
  "sua": "그의/그녀의(여)",
  "subito": "즉시",
  "sul": "~위에(su+il)",
  "suo": "그의/그녀의(남)",
  "suoi": "그의/그녀의(남복)",
  "svegli": "너는 깬다",
  "sveglio": "나는 깬다(svegliarsi)",
  "sì": "응/네",
  "tardi": "늦게",
  "tavola": "식탁",
  "tavolo": "테이블",
  "te": "너",
  "tempo": "날씨/시간",
  "ti": "너를/너에게",
  "tipo": "종류/~같은(구어)",
  "torno": "나는 돌아온다(tornare)",
  "tra": "~사이에/~후에",
  "tre": "셋",
  "trenta": "삼십",
  "tu": "너",
  "tua": "너의(여)",
  "tuo": "너의(남)",
  "tutti": "모두",
  "tutto": "모든 것/전부",
  "tè": "차",
  "umore": "기분",
  "un": "하나의(남)",
  "una": "하나의(여)",
  "uno": "하나의(남)",
  "usare": "사용하다",
  "va": "가다/괜찮다(va bene)",
  "vado": "나는 간다(andare)",
  "vedere": "보다/만나다",
  "vederti": "너를 만나는 것",
  "vedi": "너는 본다",
  "vediamo": "우리는 본다/보자",
  "vivono": "그들은 산다",
  "voi": "너희",
  "vorrei": "~하고 싶어요(정중)",
  "weekend": "주말",
  "è": "그/그녀는 ~이다",
  "aiuta": "돕는다(그/그녀)",
  "amo": "나는 좋아한다/사랑한다",
  "angolo": "모퉁이/구석",
  "anni": "년/나이(복수)",
  "aperitivo": "아페리티보(식전 한잔)",
  "apre": "연다(그/그녀)",
  "ascolto": "나는 듣는다",
  "atmosfera": "분위기",
  "autobus": "버스",
  "autunno": "가을",
  "bagno": "화장실/욕실",
  "bar": "바/카페",
  "bere": "마시다",
  "biglietti": "표(복수)",
  "biglietto": "표/티켓",
  "bisogno": "필요(avere bisogno 필요하다)",
  "blu": "파란/파랑",
  "brindiamo": "건배하자",
  "buon": "좋은",
  "buona": "좋은(여)",
  "buono": "좋은/맛있는",
  "cambiati": "변한(과거분사·복수)",
  "camminare": "걷다",
  "cantare": "노래하다",
  "canzoni": "노래들",
  "carino": "귀여운/괜찮은",
  "centro": "중심/시내",
  "cerco": "나는 찾는다",
  "chiedere": "묻다/요청하다",
  "chiedi": "너는 묻는다",
  "chilo": "킬로(그램)",
  "cioccolato": "초콜릿",
  "colore": "색깔",
  "comodi": "편한(복수)",
  "compagnia": "함께함/일행",
  "comprano": "그들은 산다",
  "compri": "너는 산다",
  "compro": "나는 산다",
  "cono": "콘",
  "contano": "중요하다(복)/세다",
  "contrattato": "흥정한",
  "coppetta": "(젤라토) 컵",
  "cose": "것들",
  "così": "이렇게/그렇게",
  "cucinare": "요리하다",
  "cucino": "나는 요리한다",
  "delle": "약간의/~의(여복)",
  "destra": "오른쪽",
  "deve": "해야 한다(그/그녀)",
  "devo": "나는 해야 한다",
  "dieci": "열(10)",
  "dipingere": "그림 그리다",
  "diversa": "다른(여)",
  "divertirti": "즐기다(너 자신)",
  "domanda": "질문",
  "dritto": "곧장/직진",
  "eccoli": "여기 있어요(그것들)",
  "eleganti": "우아한(복수)",
  "esci": "너는 나간다",
  "estate": "여름",
  "facile": "쉬운",
  "familiare": "친숙한/가족의",
  "feriali": "평일의",
  "fermata": "정류장",
  "fermate": "정류장들",
  "film": "영화",
  "fine": "끝(fine settimana 주말)",
  "fragola": "딸기",
  "freschi": "신선한(남복)",
  "freschissimi": "아주 신선한",
  "fresco": "신선한",
  "frutta": "과일",
  "funghi": "버섯(복수)",
  "gatti": "고양이들",
  "gelateria": "젤라떼리아",
  "gelato": "젤라토",
  "giri": "도세요/너는 돈다",
  "gita": "나들이/소풍",
  "gusti": "맛들/취향",
  "gusto": "맛/취향",
  "hobby": "취미",
  "idea": "생각/아이디어",
  "imbarazza": "부끄럽게 한다",
  "imparare": "배우다",
  "indicazioni": "길 안내(들)",
  "indossi": "너는 입는다",
  "ingredienti": "재료들",
  "italiane": "이탈리아의(여복)",
  "italiani": "이탈리아인/이탈리아의",
  "italiano": "이탈리아의/이탈리아어",
  "lavori": "너는 일한다/일(복수)",
  "leggere": "읽다",
  "leggo": "나는 읽는다",
  "libero": "자유로운/한가한",
  "linea": "노선/선",
  "lontano": "먼/멀리",
  "lì": "거기",
  "macchina": "자동차/기계",
  "mappe": "지도(들)",
  "mare": "바다",
  "margherita": "마르게리타(피자)",
  "maturi": "잘 익은(복)",
  "media": "중간(사이즈)/평균",
  "mele": "사과(들)",
  "mercato": "시장",
  "mezza": "반(half)",
  "mezzi": "수단(교통수단)",
  "mezzogiorno": "정오",
  "mille": "천(1000)",
  "minuti": "분(복수)",
  "moda": "패션/유행",
  "musica": "음악",
  "ne": "그 중/그것에 대해(부분 대명사)",
  "no": "아니요",
  "nove": "아홉(9)",
  "numero": "번호/숫자",
  "nuovi": "새로운(남복)",
  "ogni": "매~/모든",
  "ore": "시/시간(복수)",
  "orientamento": "방향 감각",
  "parco": "공원",
  "pasto": "식사",
  "perdi": "너는 잃는다/길을 잃다",
  "piacerebbe": "~하면 좋겠다(piacere 조건법)",
  "piazza": "광장",
  "poi": "그다음/그러고는",
  "pomodori": "토마토(들)",
  "popolare": "인기 있는/대중적인",
  "porta": "문/(사이즈를) 입다·가지고 가다",
  "porti": "너는 (사이즈를) 입다·가지고 간다",
  "preferisce": "그/그녀는 선호한다",
  "preferisco": "나는 선호한다",
  "prendere": "잡다/타다/마시다",
  "prezzo": "가격",
  "provare": "시도하다/입어보다",
  "provarla": "그것을 입어보다",
  "provi": "너는 시도한다",
  "pubblici": "공공의(복수)",
  "punto": "점/(in punto 정각)",
  "puntuale": "시간을 잘 지키는",
  "qualcosa": "무언가",
  "qualcuno": "누군가",
  "quartiere": "동네/구역",
  "quella": "저것/그것(여)",
  "qui": "여기",
  "riposare": "쉬다",
  "riposo": "나는 쉰다/휴식",
  "rosso": "빨간/빨강",
  "sabato": "토요일",
  "sai": "너는 안다",
  "salute": "건강/(salute! 건배!)",
  "scendere": "내리다",
  "senso": "감각/의미",
  "shopping": "쇼핑",
  "simile": "비슷한",
  "sinistra": "왼쪽",
  "so": "나는 안다(non lo so 모르겠어)",
  "sole": "해/태양",
  "spieghi": "너는 설명한다",
  "sposti": "너는 이동한다",
  "spritz": "스프리츠(칵테일)",
  "stato": "~한 적 있다(essere 과거분사)/상태",
  "stazione": "역",
  "strada": "길/도로",
  "strutturato": "짜임새 있는",
  "stuzzichini": "안주",
  "supermercato": "슈퍼마켓",
  "tabaccaio": "담배가게(타바키)",
  "taglia": "사이즈",
  "telefono": "전화",
  "tuoi": "너의(남복)",
  "usi": "너는 사용한다",
  "vada": "가세요(andare 존댓말 명령)",
  "vai": "너는 간다",
  "verdura": "채소",
  "vestiti": "옷(복수)",
  "vestito": "옷/원피스",
  "via": "길/거리/(via! 출발!)",
  "viene": "온다/(quanto viene 얼마예요)",
  "vita": "삶/생활/허리",
  "vivi": "너는 산다",
  "volentieri": "기꺼이/좋아요",
  "vorresti": "너는 ~하고 싶다(조건법)",
  "vuoi": "너는 원한다",
  "vuole": "그/그녀는 원한다",
  "accordo": "합의/(d'accordo 동의하는)",
  "adoro": "나는 정말 좋아한다",
  "affrontano": "그들은 직면한다",
  "ah": "아(감탄사)",
  "ali": "날개(복수)",
  "alla": "~에(a+la)",
  "ambiente": "환경",
  "andarci": "거기 가다",
  "andare": "가다",
  "andrei": "나는 갈 텐데(조건법)",
  "andresti": "너는 갈 텐데(조건법)",
  "anno": "해/년",
  "antica": "오래된(여)",
  "arrabbiato": "화난",
  "ascoltato": "들은(과거분사)",
  "ascolti": "너는 듣는다",
  "aspettiamo": "우리는 기다린다",
  "assaggiare": "맛보다",
  "assaggiarlo": "그것을 맛보다",
  "assolutamente": "절대적으로/꼭",
  "assomigliano": "그들은 닮았다",
  "attore": "배우",
  "avessi": "(내가) 가지고 있다면(접속법)",
  "avete": "너희는 가지고 있다",
  "avventura": "모험",
  "avvocato": "변호사",
  "aziende": "기업들",
  "bambino": "아이/어린이(남)",
  "banca": "은행",
  "basta": "충분하다/그만",
  "bella": "아름다운(여)",
  "belle": "아름다운(여복)",
  "bellissima": "아주 아름다운(여)",
  "cambi": "변하다(접속법)",
  "cambia": "변한다",
  "cambiare": "변하다/바꾸다",
  "cambino": "변하다(접속법 복수)",
  "cantante": "가수",
  "canticchio": "나는 흥얼거린다",
  "canzone": "노래",
  "capisco": "나는 이해한다",
  "capodanno": "새해/설날",
  "cinema": "영화관/영화",
  "città": "도시",
  "collega": "동료",
  "colori": "색깔들",
  "comodità": "편리함",
  "comodo": "편한",
  "comprato": "산(과거분사)",
  "comune": "평범한/공통의",
  "concerto": "콘서트",
  "condivido": "나는 공유한다",
  "conosciamo": "우리는 안다",
  "conosciuto": "알게 된(과거분사)",
  "consiglio": "나는 추천한다/조언",
  "contatto": "연락/접촉",
  "contro": "~에 반대하여",
  "coreano": "한국의/한국어",
  "creativo": "창의적인",
  "cuore": "마음/심장",
  "davvero": "정말로",
  "devi": "너는 ~해야 한다",
  "differenza": "차이",
  "differenze": "차이들",
  "differenziata": "분리된(raccolta differenziata 분리수거)",
  "difficile": "어려운",
  "difficoltà": "어려움",
  "dispiace": "유감이다(mi dispiace 미안하다)",
  "diventa": "~이 된다",
  "diventare": "~이 되다",
  "diventato": "~이 된(과거분사)",
  "diverse": "다른(여복)",
  "dobbiamo": "우리는 ~해야 한다",
  "doppiato": "더빙된",
  "dormire": "자다",
  "dovessi": "(내가) ~해야 한다면(접속법)",
  "dovrebbero": "그들은 ~해야 할 것이다(조건법)",
  "durante": "~동안",
  "dà": "준다(그/그녀)",
  "effetti": "영향/효과(들)",
  "emozioni": "감정들",
  "epoca": "시대",
  "equilibrio": "균형",
  "eroe": "영웅",
  "esempio": "예(per esempio 예를 들어)",
  "esprimere": "표현하다",
  "estero": "해외(all'estero 해외에서)",
  "famoso": "유명한",
  "farei": "나는 할 텐데(조건법)",
  "faresti": "너는 할 텐데(조건법)",
  "fate": "너희는 한다",
  "fatto": "한(과거분사)/사실",
  "felice": "행복한",
  "fermare": "멈추다",
  "fermerei": "나는 멈출 텐데(조건법)",
  "festa": "축제/명절/파티",
  "feste": "축제들/명절들",
  "festeggiamo": "우리는 축하한다",
  "festeggiate": "너희는 축하한다",
  "fido": "나는 믿는다(mi fido)",
  "fondo": "바닥(in fondo 사실은)",
  "foto": "사진",
  "fretta": "서두름(in fretta 빨리)",
  "funziona": "작동한다/효과 있다",
  "fuochi": "불꽃놀이/불(들)",
  "futuro": "미래",
  "genere": "장르/종류",
  "giappone": "일본",
  "giovani": "젊은이들/젊은",
  "giro": "한 바퀴(giro del mondo 세계 일주)",
  "giusto": "맞는/옳은",
  "governi": "정부들",
  "grammatica": "문법",
  "guardala": "그것을 봐",
  "guardi": "너는 본다",
  "guardo": "나는 본다",
  "hanno": "그들은 가지고 있다",
  "immagina": "상상해 봐",
  "immaginare": "상상하다",
  "imparo": "나는 배운다",
  "impegnativo": "부담되는/벅찬",
  "impegnato": "바쁜",
  "importanti": "중요한(복수)",
  "improvviso": "갑작스러운(all'improvviso 갑자기)",
  "individuali": "개인의(복수)",
  "influiscono": "그들은 영향을 준다",
  "iniziare": "시작하다",
  "inquinamento": "오염",
  "insegnante": "교사",
  "instagram": "인스타그램",
  "interessante": "흥미로운",
  "invisibile": "보이지 않는/투명한",
  "jeans": "청바지",
  "kimchi": "김치",
  "larghi": "넓은(복수)",
  "lavorare": "일하다",
  "libro": "책",
  "lingua": "언어/혀",
  "lingue": "언어들",
  "link": "링크",
  "litigato": "다툰(과거분사)",
  "lontani": "먼(복수)",
  "magari": "어쩌면/그러면 좋겠다",
  "mancato": "그리워진(과거분사)",
  "manchi": "(네가) 그립다",
  "mando": "나는 보낸다",
  "mangiato": "먹은(과거분사)",
  "mangio": "나는 먹는다",
  "medico": "의사",
  "mesi": "달(복수)",
  "messo": "놓은/넣은(과거분사)",
  "metodo": "방법",
  "mezzanotte": "자정",
  "miglioro": "나는 나아진다",
  "mode": "유행들",
  "molti": "많은(복수)",
  "mondo": "세계",
  "morto": "죽은(stanco morto 녹초)",
  "napoli": "나폴리",
  "nascondere": "숨기다",
  "nei": "~안에(in+i)",
  "nello": "~안에(in+lo)",
  "nervoso": "긴장한/초조한",
  "niente": "아무것도(아닌)",
  "nuove": "새로운(여복)",
  "opportunità": "기회",
  "ovunque": "어디든지",
  "pace": "평화(fare pace 화해하다)",
  "paesi": "나라들",
  "parla": "말한다/(이야기가) ~에 관하다",
  "parlare": "말하다",
  "parli": "너는 말한다",
  "parlo": "나는 말한다",
  "partirei": "나는 떠날 텐데(조건법)",
  "passa": "지나간다",
  "passato": "과거/지난",
  "passi": "너는 보낸다(시간)/걸음",
  "pena": "수고/가치(vale la pena)",
  "penso": "나는 생각한다",
  "piacerà": "마음에 들 것이다",
  "piccante": "매운",
  "piccole": "작은(여복)",
  "plastica": "플라스틱",
  "pop": "팝(음악)",
  "possiamo": "우리는 ~할 수 있다",
  "possibile": "가능한",
  "posti": "너는 올린다/장소(들)",
  "posto": "나는 올린다/장소/자리",
  "potessi": "(내가) ~할 수 있다면(접속법)",
  "potremmo": "우리는 ~할 수 있을 텐데(조건법)",
  "pratica": "연습",
  "preferiresti": "너는 더 좋아할 텐데(조건법)",
  "pro": "장점(pro e contro 장단점)",
  "problema": "문제",
  "proteggere": "보호하다",
  "provarlo": "그것을 시도하다",
  "proverò": "나는 시도할 것이다",
  "provo": "나는 시도한다",
  "pubblichi": "너는 게시한다",
  "può": "할 수 있다(그/그녀)",
  "qualche": "몇몇의/어떤",
  "quali": "어떤 것들",
  "quelli": "저것들/그것들",
  "raccolta": "수거/수집",
  "raccontami": "나에게 이야기해 줘",
  "ragione": "이유/(hai ragione 네 말이 맞아)",
  "realizzarmi": "나를 실현하다",
  "regalo": "선물",
  "relazioni": "관계들",
  "rende": "~하게 만든다",
  "resta": "남는다",
  "resti": "너는 남는다/머문다",
  "riciclare": "재활용하다",
  "ricicliamo": "우리는 재활용한다",
  "ridurre": "줄이다",
  "riesci": "너는 ~할 수 있다",
  "rifiuti": "쓰레기(들)",
  "rischiare": "위험을 무릅쓰다",
  "rischioso": "위험한",
  "riuniamo": "우리는 모인다",
  "riunisce": "모인다",
  "sacchetti": "봉투(들)",
  "saporito": "맛있는/풍미 있는",
  "scarichi": "너는 (스트레스를) 푼다",
  "sceglierei": "나는 고를 텐데(조건법)",
  "sceglieresti": "너는 고를 텐데(조건법)",
  "segui": "너는 팔로우한다/따른다",
  "seguiamo": "우리는 팔로우한다",
  "seguire": "따르다/팔로우하다",
  "seguo": "나는 팔로우한다",
  "sembra": "~인 것 같다",
  "senti": "너는 느낀다/들어 봐",
  "sento": "나는 느낀다(mi sento)",
  "senza": "~없이",
  "serie": "시리즈/드라마",
  "servono": "그들은 쓸모 있다/필요하다",
  "sforzi": "노력(들)",
  "sicurezza": "안정/안전",
  "simpatico": "친절한/호감 가는",
  "social": "SNS",
  "sognare": "꿈꾸다",
  "sogno": "꿈",
  "sola": "혼자의/유일한(여)",
  "soprattutto": "특히/주로",
  "sostenibile": "지속 가능한",
  "sottotitoli": "자막",
  "speciale": "특별한",
  "stanco": "피곤한",
  "stare": "있다/머물다/지내다",
  "stiamo": "우리는 있다/지낸다",
  "stile": "스타일",
  "stipendio": "월급",
  "straniera": "외국의(여)",
  "stress": "스트레스",
  "stretti": "좁은/가까운(복수)",
  "studi": "너는 공부한다/학업",
  "studio": "나는 공부한다/공부",
  "succede": "일어난다(무슨 일이)",
  "sui": "~위에/~에 대해(su+i)",
  "sulle": "~위에/~에 대해(su+le)",
  "superpotere": "초능력",
  "superpoteri": "초능력들",
  "svantaggi": "단점들",
  "tanto": "많이/매우",
  "tendenza": "트렌드",
  "tendenze": "트렌드들",
  "tornare": "돌아가다",
  "tradizione": "전통",
  "tradizioni": "전통들",
  "trama": "줄거리",
  "triste": "슬픈",
  "troppo": "너무 (많이)",
  "trovare": "찾다/발견하다",
  "tue": "너의(여복)",
  "tv": "티비",
  "ufficio": "사무실",
  "ultimo": "마지막의/최근의",
  "useresti": "너는 쓸 텐데(조건법)",
  "vale": "가치가 있다(vale la pena)",
  "vanno": "그들은 간다/(유행)이다",
  "vera": "진짜의(여)",
  "veste": "옷을 입는다(si veste)",
  "viaggerei": "나는 여행할 텐데(조건법)",
  "viaggiare": "여행하다",
  "viaggiato": "여행한(과거분사)",
  "viaggio": "여행",
  "video": "영상",
  "visto": "본(과거분사)",
  "vivaci": "선명한/생기있는(복수)",
  "vivere": "살다",
  "voglio": "나는 원한다",
  "volare": "날다",
  "volerei": "나는 날 텐데(조건법)",
  "volevi": "너는 원했다",
  "volte": "번(a volte 가끔)",
  "abbastanza": "충분히",
  "accomodatevi": "앉으세요/들어오세요",
  "acqua": "물",
  "aereo": "비행기",
  "aeroporto": "공항",
  "agli": "~에게(a+gli)",
  "ai": "~에게(a+i)",
  "aiutare": "돕다",
  "aiuto": "도움/도와주세요",
  "albergo": "호텔",
  "alleni": "너는 운동한다",
  "alleno": "나는 운동한다(mi alleno)",
  "alloggio": "숙소",
  "alta": "높은/두꺼운(여)",
  "altre": "다른(여복)",
  "amano": "그들은 좋아한다",
  "ammali": "너는 병난다(ti ammali)",
  "andata": "편도/감(andata e ritorno 왕복)",
  "animale": "동물",
  "animali": "동물들",
  "app": "앱",
  "appena": "방금/막",
  "appuntamenti": "약속들",
  "appuntamento": "약속/예약",
  "aprire": "열다",
  "arriva": "도착한다",
  "arrivano": "그들이 온다/도착한다",
  "attimo": "잠깐(un attimo 잠시만요)",
  "avevi": "너는 가지고 있었다",
  "avuto": "가진(과거분사)",
  "b": "비앤비(B&B)",
  "bancomat": "현금인출기/체크카드",
  "benvenuto": "환영해요/어서 와",
  "binario": "승강장",
  "birra": "맥주",
  "biscotti": "비스킷/과자(들)",
  "buonissima": "정말 맛있는(여)",
  "calmo": "침착한",
  "cambiato": "바꾼/환전한(과거분사)",
  "camera": "방",
  "camere": "방들",
  "campagna": "시골/전원",
  "cane": "개",
  "cani": "개들",
  "caro": "비싼/소중한",
  "carta": "카드/종이",
  "cassa": "계산대",
  "cento": "백(100)",
  "chiama": "부른다(si chiama 이름이 ~다)",
  "chiamiamo": "우리는 부른다/전화한다",
  "chiave": "열쇠",
  "chiavi": "열쇠들",
  "chiesto": "요청한/물은(과거분사)",
  "circa": "대략",
  "complimento": "칭찬",
  "comprare": "사다",
  "contanti": "현금",
  "controlli": "검진/점검(들)",
  "cornetti": "코르네토(들)",
  "correre": "달리다",
  "corro": "나는 달린다",
  "corsia": "통로/코너",
  "cortesia": "예의/친절",
  "cura": "치료/돌봄",
  "dalle": "~부터(dalle 7 7시부터)",
  "desidera": "원하세요?(존댓말)",
  "dica": "말씀하세요(mi dica)",
  "dimmi": "말해 봐",
  "disagio": "불편함(a disagio 어색한)",
  "disturbo": "방해(disturbo? 바빠?)",
  "do": "나는 준다",
  "documento": "신분증/서류",
  "dodici": "열둘(12)",
  "dolce": "단/디저트",
  "domestico": "가정의(animale domestico 반려동물)",
  "doppia": "더블의(camera doppia 더블룸)",
  "dorme": "잔다(그/그녀)",
  "dormi": "너는 잔다",
  "dormito": "잔(과거분사)",
  "dottore": "의사/박사",
  "eccolo": "여기 있어요(그것)",
  "ecologici": "친환경의(복수)",
  "emergenza": "응급/비상",
  "emergenze": "비상상황들",
  "etto": "100그램",
  "farmacia": "약국",
  "farmacie": "약국들",
  "farmacista": "약사",
  "febbre": "열",
  "felicità": "행복",
  "fermi": "세우다(si fermi 세워주세요)",
  "figurati": "별말씀을/천만에",
  "forse": "아마",
  "frigo": "냉장고",
  "gatto": "고양이",
  "gentile": "친절한",
  "gentilezze": "친절(들)",
  "gestisci": "너는 관리한다",
  "giocherellone": "장난꾸러기인",
  "girare": "돌다/돌아다니다",
  "gola": "목/목구멍",
  "grande": "큰",
  "guarda": "봐 봐",
  "guardiamo": "우리는 본다/보자",
  "guarirà": "나을 것이다",
  "ideale": "이상적인",
  "identità": "신원(documento d'identità 신분증)",
  "inclusa": "포함된(여)",
  "ingrediente": "재료",
  "ingresso": "입구",
  "invitato": "초대받은",
  "inviti": "너는 초대한다",
  "invito": "초대",
  "lasci": "너는 남긴다/(팁을) 준다",
  "latte": "우유",
  "lista": "목록",
  "luminosa": "환한/밝은(여)",
  "mal": "아픔(mal di testa 두통)",
  "male": "나쁘게/아프게(sto male 아파요)",
  "mancia": "팁",
  "margherite": "마르게리타(들)",
  "medicina": "약",
  "medicine": "약(들)",
  "messaggi": "메시지들",
  "messaggiare": "메시지를 보내다",
  "mezzo": "절반(mezzo chilo 500그램)",
  "milano": "밀라노",
  "naturali": "자연의(복수)",
  "nome": "이름",
  "numeri": "번호/숫자(들)",
  "nuoto": "수영",
  "occupata": "통화 중인/사용 중인(여)",
  "offerta": "할인/제안",
  "oggetti": "물건들(oggetti smarriti 분실물)",
  "oh": "오(감탄사)",
  "online": "온라인",
  "ordinate": "너희는 주문한다",
  "organizzarsi": "일정을 잡다/준비하다",
  "padrone": "주인(padrone di casa 집주인/호스트)",
  "pagare": "지불하다",
  "paghi": "너는 낸다",
  "palestra": "헬스장",
  "pallido": "창백한",
  "panificio": "빵집",
  "parte": "출발한다/부분",
  "partita": "경기",
  "pastiglia": "알약",
  "pazienza": "인내/양해",
  "periodo": "시기",
  "perso": "잃은(과거분사)",
  "piano": "층/천천히",
  "polizia": "경찰",
  "pomeriggio": "오후",
  "portafoglio": "지갑",
  "portare": "가져오다/데려가다",
  "porto": "나는 가져간다/데려간다",
  "possono": "그들은 ~할 수 있다",
  "prelevare": "출금하다",
  "prenda": "드세요/잡으세요(존댓말)",
  "prende": "잡는다/주문한다(그/그녀)",
  "prenotare": "예약하다",
  "prenotazione": "예약",
  "prepari": "너는 준비한다",
  "prevenzione": "예방",
  "prodotti": "제품들",
  "profumo": "향기",
  "pronto": "여보세요?/준비된",
  "pure": "~도/편하게(dimmi pure 편히 말해)",
  "raffreddore": "감기",
  "responsabilità": "책임",
  "resto": "거스름돈/나머지",
  "ricetta": "처방전/조리법",
  "richiamo": "나는 다시 전화한다",
  "rifiutare": "거절하다",
  "rimandato": "미룬(과거분사)",
  "rimedi": "치료법들(rimedi naturali 자연요법)",
  "ringrazi": "너는 감사한다",
  "riposi": "쉬세요(존댓말)",
  "risparmiare": "저축하다/아끼다",
  "rispondi": "너는 답한다",
  "ritardo": "지연(in ritardo 지연된)",
  "salato": "짠/짭짤한",
  "salotto": "거실",
  "salta": "건너뛴다/취소된다",
  "sbagli": "너는 실수한다",
  "scomodo": "불편한",
  "sconosciuti": "모르는(복수)",
  "scrivere": "쓰다",
  "scusarsi": "사과하다",
  "sente": "느낀다/(어떠세요 cosa sente)",
  "serve": "필요하다/쓸모 있다",
  "sfornato": "갓 구운(appena sfornato)",
  "sia": "~이다(접속법)/그것이든",
  "sintomi": "증상들",
  "smarriti": "분실된(oggetti smarriti 분실물)",
  "soldi": "돈",
  "sottile": "얇은",
  "spasso": "산책(portare a spasso 산책시키다)",
  "spendi": "너는 (돈을) 쓴다",
  "spesa": "장보기",
  "spiegare": "설명하다",
  "sport": "스포츠/운동",
  "spostare": "옮기다/미루다",
  "squadra": "팀",
  "stamattina": "오늘 아침",
  "stanza": "방",
  "stessi": "(내가) ~한다면(접속법, se stessi male)",
  "sto": "나는 있다/지낸다(sto bene)",
  "stomaco": "위/배",
  "sull": "~위에(su+l')",
  "sulla": "~위에(su+la)",
  "tassista": "택시 기사",
  "taxi": "택시",
  "telefonare": "전화하다",
  "telefoni": "너는 전화한다",
  "tenga": "가지세요(존댓말, tenga pure)",
  "testa": "머리",
  "tieni": "너는 가지고 있다/둔다",
  "tranquillo": "안심해/괜찮아",
  "treno": "기차",
  "ultima": "마지막의(여, l'ultima volta 지난번)",
  "uova": "달걀(들)",
  "uscire": "나가다",
  "uscita": "출구",
  "veloce": "빠른/빠르게",
  "venire": "오다",
  "vergogni": "너는 부끄러워한다(ti vergogni)",
  "verso": "~쯤/~을 향해",
  "viaggi": "너는 여행한다/여행(들)",
  "vicino": "가까운/근처",
  "vieni": "너는 온다/와",
  "vocali": "음성의(messaggi vocali 음성 메시지)",
  "volta": "번/회(una volta 한 번)",
  "accettare": "받아들이다",
  "acquisto": "구매",
  "adulazione": "아부",
  "affittare": "임대하다",
  "affitto": "월세",
  "aggiungi": "넣어/추가해",
  "aiutate": "너희는 돕는다(vi aiutate 서로 돕다)",
  "alto": "키 큰/높은",
  "antipasto": "전채",
  "aperta": "개방적인/열린(여)",
  "appartamento": "아파트",
  "aprilo": "그것을 열어 봐",
  "arredato": "가구가 있는",
  "arrossire": "얼굴이 빨개지다",
  "arte": "예술",
  "aspetto": "외모/모습",
  "assaggia": "맛봐",
  "assomigli": "너는 닮았다",
  "auguri": "축하/축원",
  "azzurri": "하늘색의(복수)",
  "batteria": "배터리",
  "bellissimo": "정말 아름다운",
  "benissimo": "아주 잘",
  "bollire": "끓이다",
  "bravo": "잘한다/대단한",
  "bruschette": "브루스케타(들)",
  "calda": "뜨거운/따뜻한(여)",
  "calma": "평온/침착(con calma 천천히)",
  "cambieresti": "너는 바꿀 텐데(조건법)",
  "cambio": "변화/교체(cambio di stagione 환절기)",
  "camerino": "탈의실",
  "candeline": "(생일) 초",
  "capelli": "머리카락",
  "carattere": "성격",
  "caricabatterie": "충전기",
  "caricare": "충전하다/싣다",
  "cartoline": "엽서(들)",
  "ce": "(ce l'ha 그것을 가지고 있다)",
  "cellulare": "휴대폰",
  "cercato": "찾은(과거분사)",
  "chiude": "닫는다",
  "coinquilini": "룸메이트(들)",
  "compiere": "(나이를) 채우다(compiere gli anni 나이를 먹다)",
  "compleanno": "생일",
  "completamente": "완전히",
  "complimenti": "칭찬(들)",
  "comprarli": "그것들을 사다",
  "consigli": "조언(들)",
  "consiglia": "추천한다(그/그녀)",
  "contorno": "곁들임/반찬",
  "corti": "짧은(복수)",
  "cuocio": "나는 익힌다/요리한다",
  "dai": "너는 준다(mi dai 줄래)",
  "dalla": "~부터(da+la)",
  "davanti": "앞에/앞쪽",
  "diciotto": "열여덟(18)",
  "dico": "나는 말한다(dico sul serio 진심이야)",
  "dietro": "뒤에/뒤쪽",
  "disegnare": "그림 그리다",
  "dispiacerebbe": "유감일 텐데(조건법)",
  "dispositivo": "기기/장치",
  "diverso": "다른",
  "dovevi": "너는 ~해야 했다(non dovevi 안 그래도 됐는데)",
  "dura": "지속된다(dura poco 금방 닳다)",
  "escluse": "제외된(여복, spese escluse 관리비 별도)",
  "famosi": "유명한(복수)",
  "farti": "너에게 ~하다(farti un complimento 칭찬하다)",
  "festeggi": "너는 축하한다/기념한다",
  "fidi": "너는 믿는다(ti fidi 신뢰하다)",
  "fortunati": "운 좋은(복수)",
  "francobollo": "우표",
  "generoso": "너그러운",
  "gliela": "그것을 그에게(gliela porto 가져다드리다)",
  "griglia": "그릴(alla griglia 구이)",
  "guida": "가이드/안내서",
  "guidata": "안내를 받는(visita guidata 가이드 투어)",
  "incluse": "포함된(여복, spese incluse 관리비 포함)",
  "informazioni": "정보",
  "inizio": "시작(all'inizio 처음에)",
  "insalata": "샐러드",
  "interi": "일반(요금)의(복수)",
  "intero": "일반(요금)/전체",
  "inverno": "겨울",
  "largo": "헐렁한/넓은",
  "li": "그것들을(목적격)",
  "libera": "자유로운(여, visita libera 자유 관람)",
  "lui": "그(남)",
  "luminoso": "환한/밝은",
  "maglietta": "티셔츠",
  "mappa": "지도",
  "marroni": "갈색의(복수)",
  "medium": "미디엄(사이즈)",
  "mese": "달/월",
  "migliore": "가장 좋은(il migliore 최고의)",
  "monolocale": "원룸",
  "montagna": "산",
  "mostra": "전시",
  "musei": "박물관들",
  "museo": "박물관",
  "nascosti": "숨겨진(복수)",
  "naturale": "천연의/무탄산의(acqua naturale 무탄산수)",
  "negozi": "가게들",
  "negozio": "가게",
  "né": "~도 아닌(né…né 둘 다 아닌)",
  "occhi": "눈(복수)",
  "ombrellone": "파라솔",
  "opera": "작품",
  "opposto": "정반대",
  "ordine": "순서/주문",
  "ordini": "너는 주문한다",
  "osare": "과감히 시도하다",
  "paese": "나라/마을",
  "parrucchiere": "미용사/미용실",
  "pentito": "후회한(과거분사)",
  "periferia": "외곽",
  "pettinatura": "머리 모양",
  "pianifichi": "너는 계획한다",
  "piatti": "요리들/접시들",
  "piccoli": "작은(복수)",
  "piega": "드라이/세팅",
  "pomodoro": "토마토",
  "portate": "코스 요리들(a portate 코스로)",
  "preciso": "정확한(di preciso 구체적으로)",
  "primavera": "봄",
  "problemi": "문제들",
  "quant": "얼마(quant'è 얼마예요)",
  "quel": "그/저(quel colore 그 색)",
  "quindici": "열다섯(15)",
  "rapporti": "관계들",
  "reso": "만든(과거분사, ha reso ~하게 만들었다)",
  "ricarica": "충전(휴대폰)",
  "ricci": "곱슬의(복수)",
  "ricette": "레시피들",
  "ricevi": "너는 받는다",
  "riconosci": "너는 알아본다",
  "ricordi": "너는 기억한다/추억(들)",
  "ridotti": "할인(요금)의(복수)",
  "ridotto": "할인(요금)",
  "rilassarsi": "긴장을 풀다",
  "risolvi": "너는 해결한다",
  "risotto": "리소토",
  "ritorno": "돌아옴(andata e ritorno 왕복)",
  "rumore": "소음",
  "sabbia": "모래",
  "sale": "소금",
  "saranno": "~일 것이다(복수 미래)",
  "sarà": "~일 것이다(미래)",
  "scarico": "나는 내려받는다/(스트레스를) 푼다",
  "scarpe": "신발(들)",
  "schermo": "화면",
  "sdraio": "비치 의자",
  "seicento": "육백(600)",
  "serio": "진지한(sul serio 진심으로)",
  "simpatica": "친절한/호감 가는(여)",
  "sincero": "진심 어린",
  "sistemi": "너는 정돈한다(ti sistemi 손질하다)",
  "socievole": "사교적인",
  "sorpresa": "놀람/서프라이즈(festa a sorpresa 깜짝 파티)",
  "sorriso": "미소",
  "sparissero": "사라진다면(접속법)",
  "spegni": "꺼/불어 꺼",
  "spese": "비용/관리비(들)",
  "spiaggia": "해변",
  "spuntatina": "살짝 다듬기",
  "stagioni": "계절들",
  "stili": "스타일들",
  "storia": "역사/이야기",
  "storico": "역사적인(centro storico 구시가지)",
  "stretta": "끼는/좁은(여)",
  "studenti": "학생들",
  "sugo": "소스",
  "tabaccheria": "타바케리아(담배·표 가게)",
  "tagliare": "자르다",
  "taglio": "커트/스타일",
  "tante": "많은(여복)",
  "tanti": "많은(복수, tanti auguri 축하)",
  "tecnologia": "기술",
  "timida": "수줍은(여)",
  "timido": "수줍은",
  "trasferito": "이사한(과거분사)",
  "trovi": "너는 찾는다/발견한다",
  "turistico": "관광의(ufficio turistico 관광 안내소)",
  "usato": "사용한(과거분사)",
  "vende": "판다(si vende 팔리다)",
  "verdi": "초록색의(복수)",
  "verdure": "채소(들)",
  "vero": "진짜의/사실",
  "vi": "너희를/너희에게",
  "vicini": "이웃들/가까운(복수)",
  "visita": "방문/관람",
  "visiti": "너는 방문한다",
  "vongole": "바지락(들)",
  "abbelliscano": "미화되다(접속법)",
  "abbiamo": "우리는 가지고 있다",
  "abbini": "너는 짝짓다/매치하다",
  "abitavo": "나는 살았다(반과거)",
  "abituando": "익숙해지는 중(mi sto abituando)",
  "abitudine": "습관",
  "abitudini": "습관들",
  "abituo": "나는 익숙해진다(mi abituo)",
  "accompagnare": "동반하다/곁들이다",
  "ad": "~에(a, 모음 앞)",
  "adattarsi": "적응하다",
  "affare": "좋은 거래/횡재",
  "affetto": "애정",
  "affidabili": "믿을 만한(복수)",
  "agriturismo": "농가 숙소",
  "allo": "~에/~로(a+lo)",
  "altri": "다른 사람들/다른 것들",
  "altrui": "남의/타인의",
  "amicizia": "우정",
  "amore": "사랑",
  "andate": "너희는 간다(andate d'accordo 사이좋다)",
  "andato": "간(과거분사)",
  "andavi": "너는 갔다(반과거, andavi bene 잘했다)",
  "andrà": "~일 것이다(미래)",
  "andrò": "나는 갈 것이다",
  "anziani": "어르신들",
  "arrivare": "도착하다",
  "attivo": "활동적인",
  "bei": "멋진/좋은(복수, bei tempi 좋은 시절)",
  "bevuto": "마신(과거분사)",
  "bianco": "흰/화이트(와인)",
  "bisogna": "~해야 한다(일반적 필요)",
  "bocca": "입(in bocca al lupo 행운을 빌어)",
  "calcio": "축구",
  "capacità": "능력",
  "cartolina": "엽서",
  "cenano": "그들은 저녁을 먹는다",
  "cenate": "너희는 저녁을 먹는다",
  "ceniamo": "우리는 저녁을 먹는다",
  "cercavamo": "우리는 찾고 있었다(반과거)",
  "clima": "기후/날씨",
  "colleghi": "동료들",
  "colpo": "타격(colpo di fulmine 첫눈에 반함)",
  "concentrarti": "집중하다(ti concentri)",
  "contrario": "반대(al contrario 반대로)",
  "cotta": "짝사랑/반함",
  "credi": "너는 믿는다",
  "credo": "나는 믿는다/~같다",
  "cui": "(관계대명사, a cui ~에게)",
  "degli": "~의(di+gli)",
  "distanza": "거리(a distanza 원거리의)",
  "divertente": "재미있는",
  "documenti": "서류들",
  "dovremmo": "우리는 ~해야 할 텐데(조건법)",
  "edicola": "신문 가판대",
  "educato": "예의 바른",
  "email": "이메일",
  "eravamo": "우리는 ~였다(반과거)",
  "ero": "나는 ~였다(반과거)",
  "esame": "시험",
  "esami": "시험들",
  "esprimi": "너는 표현한다",
  "essermi": "(essermi innamorato 사랑에 빠진)",
  "estati": "여름들",
  "farai": "너는 할 것이다",
  "fascino": "매력",
  "fatta": "만들어진(여, fatta in casa 수제의)",
  "felici": "행복한(복수)",
  "fidanzato": "남자친구/약혼자",
  "finale": "결승/마지막",
  "finalmente": "드디어",
  "fulmine": "번개(colpo di fulmine 첫눈에 반함)",
  "funzionare": "작동하다/잘 되다",
  "galateo": "예절/매너",
  "gesto": "행동/제스처",
  "giocavamo": "우리는 놀았다(반과거)",
  "giocavi": "너는 놀았다(반과거)",
  "giocavo": "나는 놀았다(반과거)",
  "giornale": "신문",
  "giornali": "신문들",
  "giudicano": "그들은 판단한다",
  "gol": "골",
  "guardare": "보다",
  "imparato": "배운(과거분사)",
  "improvvisare": "즉흥적으로 하다",
  "inizi": "너는 시작한다/시작(들)",
  "innamorato": "사랑에 빠진",
  "intenzione": "의도(ho intenzione di ~할 생각이다)",
  "interrompere": "끼어들다/방해하다",
  "lampada": "램프/조명",
  "lascia": "남긴다/(팁을) 준다",
  "legati": "가까운/친밀한(복수)",
  "legato": "가까운/친밀한",
  "leggi": "너는 읽는다",
  "lenta": "느린(여)",
  "lettera": "편지",
  "locale": "지역의/현지의",
  "locali": "지역의(복수, prodotti locali 특산물)",
  "loro": "그들/그들의",
  "lungo": "긴(a lungo 오래)",
  "lupo": "늑대(in bocca al lupo 행운을 빌어)",
  "mail": "메일",
  "maleducato": "무례한",
  "manca": "부족하다/그립다(mi manca 그리워)",
  "mandare": "보내다",
  "mandi": "너는 보낸다(mi mandi 보내줄래)",
  "materia": "과목",
  "materie": "과목들",
  "mercatino": "벼룩시장",
  "modo": "방식(in modo diverso 다르게)",
  "mostrano": "그들은 보여준다",
  "natura": "자연",
  "nonna": "할머니",
  "notizie": "뉴스(들)",
  "obbligatorio": "의무적인",
  "pacchi": "소포들",
  "pacco": "소포",
  "parto": "나는 떠난다",
  "passatempo": "취미/소일거리",
  "pausa": "휴식/쉬는 시간",
  "perfetta": "완벽한(여)",
  "piacevano": "좋아했다(반과거, mi piacevano)",
  "posta": "우편/우체국",
  "potete": "너희는 ~할 수 있다",
  "presente": "현재",
  "progetto": "계획/프로젝트",
  "programmare": "계획하다",
  "programmi": "계획들",
  "promosso": "합격한/진급한",
  "prossimo": "다음의",
  "quadro": "그림/액자",
  "quest": "이(quest'anno 올해)",
  "questione": "문제/사안(questione di abitudine 습관 문제)",
  "raccomandata": "등기",
  "regole": "규칙들",
  "relazione": "관계/연애",
  "ricordo": "추억/기억",
  "rilassarti": "쉬다(ti rilassi)",
  "rilasso": "나는 쉰다(mi rilasso)",
  "rimandare": "미루다",
  "rischia": "위험을 무릅쓴다(si rischia 위험이 있다)",
  "rispettare": "존중하다",
  "rispetto": "존중",
  "ritmi": "리듬들",
  "riunione": "회의",
  "rivista": "잡지",
  "riviste": "잡지들",
  "sala": "홀/회의실",
  "saluta": "인사한다(ci si saluta 서로 인사하다)",
  "sbagliare": "실수하다",
  "scadenza": "마감",
  "scalda": "데운다/마음을 데운다",
  "sconto": "할인(fare uno sconto 깎아주다)",
  "scuola": "학교",
  "secco": "드라이한/건조한",
  "sfogliare": "(책장을) 넘겨 보다",
  "sogni": "너는 꿈꾼다/꿈(들)",
  "soli": "혼자(복수, da soli 혼자서)",
  "sparirà": "사라질 것이다",
  "sparisse": "사라진다면(접속법)",
  "spedire": "부치다/보내다",
  "spedito": "부친(과거분사)",
  "speriamo": "우리는 바란다/그러길",
  "stadio": "경기장",
  "stampata": "인쇄된(carta stampata 종이 매체)",
  "stasera": "오늘 밤",
  "stata": "있었던/간(여, 과거분사)",
  "strano": "이상한/신기한",
  "studiare": "공부하다",
  "studiato": "공부한(과거분사)",
  "tanta": "많은(여)",
  "tempi": "시절/시대(들)",
  "templi": "신전들",
  "tendi": "너는 ~하는 경향이 있다(tendi a)",
  "tifi": "너는 응원한다",
  "tornarci": "거기 다시 가다",
  "torneresti": "너는 돌아갈 텐데(조건법)",
  "torta": "케이크",
  "tranquillità": "평온함",
  "troverete": "너희는 찾을 것이다",
  "tutta": "전체의(여, tutta la sera 저녁 내내)",
  "ultimamente": "최근에",
  "unisce": "하나로 묶는다/단결시킨다",
  "usa": "사용한다(si usa 관습이다)",
  "usanza": "관습/풍습",
  "usciamo": "우리는 나간다/나가자",
  "usiamo": "우리는 사용한다",
  "vacanza": "휴가",
  "vacanze": "휴가(들)",
  "vecchi": "오래된(복수)",
  "vecchie": "오래된(여복)",
  "vedo": "나는 본다(ti vedo 너 ~해 보여)",
  "vedrai": "너는 볼 것이다(두고 봐)",
  "venerdì": "금요일",
  "venti": "스물(20)",
  "vino": "와인",
  "vinto": "이긴(과거분사)",
  "visitato": "방문한(과거분사)",
  "vivo": "나는 산다",
  "vogliono": "그들은 원한다(si vogliono bene 서로 아낀다)",
  "abito": "나는 산다(abitare)",
  "adatti": "너는 적응한다(ti adatti)",
  "aiuteranno": "그들은 도울 것이다",
  "aiutiamo": "우리는 돕는다",
  "altra": "다른(여)",
  "arricchisce": "풍요롭게 한다",
  "arrivo": "나는 도착한다/도착",
  "artificiale": "인공의(intelligenza artificiale 인공지능)",
  "artista": "예술가",
  "associazione": "단체",
  "attenti": "조심하는(복수, stare attenti 조심하다)",
  "attività": "활동",
  "aumenta": "증가시킨다",
  "autore": "작가",
  "avvicina": "가깝게 만든다",
  "bambini": "아이들",
  "banane": "바나나(들)",
  "benessere": "웰빙/안녕",
  "biologica": "유기농의(여)",
  "brutte": "나쁜(여복, brutte notizie 나쁜 소식)",
  "cambierei": "나는 바꿀 텐데(조건법)",
  "cambieremo": "우리는 바꿀 것이다",
  "cambierà": "바뀔 것이다",
  "cammini": "너는 걷는다",
  "canale": "채널",
  "canali": "채널들",
  "capo": "우두머리/처음(da capo 처음부터)",
  "carina": "예쁜(여)",
  "chissà": "누가 알겠어/글쎄",
  "cinquant": "오십(cinquant'anni 50년)",
  "civiltà": "문명",
  "coltello": "칼",
  "connessi": "연결된(복수)",
  "consegna": "배달/배송",
  "consegne": "배달(들)",
  "contate": "믿으세요/기대세요(contate su di me)",
  "contenuto": "콘텐츠/내용",
  "conveniente": "저렴한/이득인",
  "convivere": "함께 살다/공존하다",
  "coraggio": "용기",
  "creiamo": "우리는 만든다",
  "dall": "~로부터(da+l')",
  "darsi": "(può darsi 그럴 수도 있다)",
  "dello": "~의(di+lo)",
  "deserta": "인적 없는(여, isola deserta 무인도)",
  "dieta": "식단/다이어트",
  "dipendenza": "의존/중독",
  "diretto": "직행의/직접의",
  "diritto": "권리",
  "diversità": "다양성",
  "dolcissime": "아주 단(여복)",
  "domicilio": "집/거주지(a domicilio 집으로)",
  "dovrei": "나는 ~해야 할 텐데(조건법)",
  "ebook": "전자책",
  "ed": "그리고(e, 모음 앞)",
  "educare": "교육하다",
  "educazione": "교육/교양",
  "entusiasma": "열광시킨다",
  "episodio": "에피소드",
  "equità": "공정",
  "esagerare": "과하게 하다",
  "esatto": "맞아요/정확해요",
  "false": "가짜의(여복, notizie false 가짜 뉴스)",
  "fanno": "그들은 한다",
  "fantastico": "환상적인",
  "faranno": "그들은 할 것이다",
  "faremo": "우리는 할 것이다",
  "fette": "(얇은) 조각들",
  "fidare": "믿다(ci si può fidare 믿을 수 있다)",
  "finisco": "나는 끝낸다",
  "forza": "힘",
  "fruttivendolo": "과일가게/과일장수",
  "glielo": "그것을 그에게/그녀에게",
  "gratis": "공짜의",
  "grave": "심각한",
  "ia": "인공지능(IA)",
  "illimitati": "무한한(복수)",
  "immaginato": "상상한(과거분사)",
  "impressionante": "인상적인/놀라운",
  "iniziativa": "활동/이니셔티브",
  "intelligenza": "지능(intelligenza artificiale 인공지능)",
  "interessano": "그것들이 관심을 끈다(mi interessano)",
  "iscritto": "등록한/구독한(과거분사)",
  "iscrivo": "나는 구독한다(mi iscrivo)",
  "isola": "섬",
  "lasceresti": "너는 두고 갈 텐데(조건법)",
  "lavoreranno": "그들은 일할 것이다",
  "leggendo": "읽고 있는(sto leggendo)",
  "letta": "읽힌(여, 과거분사)",
  "letto": "읽은(과거분사)/침대",
  "libri": "책들",
  "macellaio": "정육점 주인",
  "macino": "내가 갈다(glielo macino 갈아드릴까요)",
  "mancano": "부족하다/남았다(quante fermate mancano)",
  "mancherebbe": "그리울 텐데(mi mancherebbe)",
  "manzo": "소고기",
  "mature": "잘 익은(여복)",
  "meditazione": "명상",
  "mente": "마음/정신",
  "mentre": "~하는 동안",
  "metropolitana": "지하철",
  "nascere": "태어나다",
  "notizia": "뉴스/소식",
  "novità": "새로운 것/소식",
  "ordino": "나는 주문한다",
  "orientarsi": "길을 찾다/방향을 잡다",
  "orienti": "너는 길을 찾는다(ti orienti)",
  "ottime": "아주 좋은(여복)",
  "parità": "평등",
  "partecipare": "참여하다",
  "passo": "걸음/단계(primo passo 첫걸음)",
  "podcast": "팟캐스트",
  "pollo": "닭고기",
  "porterei": "나는 가져갈 텐데(조건법)",
  "porteresti": "너는 가져갈 텐데(조건법)",
  "pregiudizi": "편견들",
  "pregiudizio": "편견",
  "preoccupa": "걱정시킨다(mi preoccupa 걱정돼)",
  "privacy": "사생활",
  "progresso": "발전/진보",
  "prossima": "다음의(여, alla prossima 다음 역에)",
  "provato": "시도한/써본(과거분사)",
  "pubblico": "공공의/대중(trasporto pubblico 대중교통)",
  "qualità": "품질",
  "queste": "이것들(여)",
  "ragù": "라구(고기 소스)",
  "reciproco": "상호의(rispetto reciproco 상호 존중)",
  "resisto": "나는 버틴다",
  "ricchezza": "풍요로움/부",
  "ricominceresti": "너는 다시 시작할 텐데(조건법)",
  "ricominciare": "다시 시작하다",
  "riduce": "줄인다",
  "rilassarmi": "긴장을 풀다(mi rilasso)",
  "rischio": "위험",
  "risolti": "해결된(복수)",
  "riusciresti": "너는 해낼 텐데(조건법)",
  "robot": "로봇",
  "romanzo": "소설",
  "rossa": "빨간(여, linea rossa 빨간 노선)",
  "sane": "건강한(여복, abitudini sane 건강한 습관)",
  "sarebbe": "~일 텐데(조건법)",
  "scenda": "내리세요(존댓말 명령)",
  "schermi": "화면들",
  "sentito": "들은/느낀(과거분사)",
  "società": "사회",
  "solidarietà": "연대",
  "solitudine": "외로움",
  "sopravviveresti": "너는 살아남을 텐데(조건법)",
  "staccare": "(일에서) 벗어나다/끊다",
  "stessa": "같은(여, la stessa cosa 같은 것)",
  "stesse": "같은(여복, le stesse opportunità 같은 기회)",
  "successo": "일어난(과거분사)/성공",
  "tantissimo": "엄청나게",
  "tech": "기술(tech)",
  "telegiornale": "TV 뉴스",
  "tranquilla": "조용한(여)",
  "trasporto": "교통/운송",
  "tratta": "다룬다(si tratta di ~에 관한 것이다)",
  "troppe": "너무 많은(여복)",
  "tutte": "모든(여복)",
  "uguaglianza": "평등",
  "uso": "나는 사용한다/사용",
  "utile": "유용한",
  "valore": "가치",
  "vegetariana": "채식의(여)",
  "verificare": "확인하다/검증하다",
  "verissimo": "정말 맞아요",
  "vive": "산다(si vive bene 살기 좋다)",
  "vivranno": "그들은 살 것이다",
  "vivremo": "우리는 살 것이다",
  "volontariato": "자원봉사",
  "yoga": "요가",
  "corpo": "몸/신체",
  "affidabile": "믿음직한",
  "aiutarla": "그녀를 돕다/도와드리다",
  "aiutato": "도운(과거분사)",
  "alba": "새벽",
  "alimentari": "식품의/음식의(mode alimentari 음식 유행)",
  "ama": "사랑한다(그/그녀)",
  "ammiri": "너는 존경한다",
  "ammiro": "나는 존경한다",
  "anticipo": "미리/앞당김(in anticipo 일찍)",
  "arrabbi": "너는 화낸다(ti arrabbi)",
  "arrivi": "너는 도착한다",
  "attenzione": "주의(fare attenzione 신경 쓰다)",
  "aumentino": "오르다(접속법, prima che aumentino 오르기 전에)",
  "avevo": "나는 가지고 있었다(반과거)",
  "bucato": "빨래(fare il bucato 빨래하다)",
  "candido": "나는 지원한다(mi candido)",
  "cenare": "저녁을 먹다",
  "cerca": "찾는다(그/그녀)",
  "chiarire": "(오해를) 풀다/분명히 하다",
  "chiederei": "나는 물어볼 텐데(조건법)",
  "chiederesti": "너는 물어볼 텐데(조건법)",
  "colloquio": "면접",
  "compagni": "동기/급우들",
  "comportarsi": "행동하다/처신하다",
  "conoscerlo": "그를 알다",
  "contagiosa": "전염성 있는(여)",
  "contare": "세다/(contare su 의지하다)",
  "convinto": "설득한/확신한(과거분사)",
  "corso": "강의/과정",
  "costruisce": "세운다/쌓는다(si costruisce 쌓이다)",
  "creatività": "창의성",
  "crescere": "자라다/성장하다",
  "decide": "결정한다",
  "deludere": "실망시키다",
  "deluderò": "나는 실망시킬 것이다",
  "digitali": "디지털의(복수)",
  "dipende": "~에 따라 다르다",
  "diretta": "직접적인(여, esperienza diretta 직접 경험)",
  "dirti": "너에게 말하다",
  "disponibile": "가능한/시간이 되는",
  "efficace": "효과적인",
  "era": "~였다(반과거)",
  "esagerato": "과하게 한(과거분사, ho esagerato 내가 심했어)",
  "esistere": "존재하다",
  "esperienza": "경험/경력",
  "esperienze": "경험들",
  "faccenda": "집안일/볼일",
  "facilmente": "쉽게",
  "farla": "그것을 하다(fare la fila 줄 서기)",
  "fiducia": "신뢰",
  "fila": "줄(fare la fila 줄을 서다)",
  "forte": "크게/강한",
  "fotografare": "사진 찍다",
  "fotografi": "너는 사진 찍는다",
  "generalizzare": "일반화하다",
  "genio": "천재",
  "gentilezza": "친절",
  "gentili": "친절한(복수)",
  "giovedì": "목요일",
  "giugno": "6월",
  "gratificante": "보람 있는",
  "gratificato": "보람을 느끼는",
  "hotel": "호텔",
  "idolo": "우상/롤모델",
  "impari": "너는 배운다",
  "incontrare": "만나다",
  "influenza": "영향을 준다/독감",
  "interessa": "관심을 끈다(mi interessa)",
  "ispira": "영감을 준다(mi ispira)",
  "laurei": "너는 졸업한다(ti laurei)",
  "laureo": "나는 졸업한다(mi laureo)",
  "lavanderia": "세탁소",
  "lavare": "빨다/세탁하다",
  "leggero": "가벼운/담백한",
  "letteratura": "문학",
  "lezione": "수업",
  "litigare": "다투다",
  "litighi": "너는 다툰다",
  "litigio": "다툼",
  "luogo": "장소(luogo comune 흔한 오해)",
  "macchia": "얼룩",
  "mangiano": "그들은 먹는다",
  "mano": "손(una mano 도움)",
  "mantenere": "유지하다/지키다(segreto)",
  "marchio": "브랜드/상표",
  "mattino": "아침",
  "meta": "여행지/목적지",
  "molte": "많은(여복)",
  "nascono": "생겨난다/태어난다",
  "negli": "~안에(in+gli)",
  "nemmeno": "~도 아니다(nemmeno io 나도 아니야)",
  "nessuno": "아무도(아닌)",
  "normale": "보통의/정상의",
  "nostre": "우리의(여복)",
  "organizzi": "너는 준비한다/조직한다",
  "paesaggi": "풍경들",
  "paesaggio": "풍경",
  "paga": "낸다(si paga 지불한다)",
  "parlarne": "그것에 대해 말하다",
  "parliamone": "그것에 대해 얘기하자",
  "particolare": "특별한/특정한(in particolare 특히)",
  "pensato": "생각한(과거분사)",
  "pericolosi": "위험한(복수)",
  "persa": "잃은(여, 과거분사)",
  "personale": "개인의",
  "pesa": "무겁다/부담된다",
  "pesante": "무거운",
  "portato": "가져온/맡긴(과거분사)",
  "positivo": "긍정적인",
  "potrebbe": "~할 수도 있다(조건법)",
  "precisione": "꼼꼼함/정확성",
  "pregi": "장점들",
  "premuroso": "배려심 있는",
  "prenotato": "예약한(과거분사)",
  "prenotiamo": "우리는 예약한다/예약하자",
  "pronta": "준비된(여)",
  "pronti": "준비된(복수)",
  "propri": "자신의(복수)",
  "proprio": "바로/정말(proprio lui 하필 그 사람)",
  "pubblicità": "광고",
  "puntuali": "시간을 지키는(복수)",
  "puoi": "너는 ~할 수 있다",
  "quindi": "그래서/그러면",
  "raccomando": "당부한다(mi raccomando 꼭이야)",
  "rafforzare": "강화하다",
  "rapporto": "관계",
  "regione": "지역/주",
  "rendono": "~하게 만든다(복수)",
  "riconquistare": "되찾다",
  "rimasto": "남은(과거분사, mi è rimasto in mente 기억에 남았어)",
  "riso": "쌀/밥",
  "risultato": "결과",
  "ritirarla": "그것을 찾아가다",
  "ritirarlo": "그것을 찾아가다",
  "rompe": "깨진다(si rompe)",
  "ruolo": "역할/직책",
  "sano": "건강한",
  "scattata": "찍힌(여, 과거분사)",
  "scatto": "나는 (사진을) 찍는다",
  "scelte": "선택들",
  "sconosciuto": "낯선 사람/모르는",
  "scusarmi": "사과하다(mi scuso)",
  "scusarti": "사과하다(ti scusi)",
  "segreto": "비밀",
  "settore": "분야/업계",
  "silenzio": "침묵",
  "situazioni": "상황들",
  "soddisfatto": "만족한",
  "soddisfazione": "만족",
  "somigliamo": "우리는 닮았다(ci somigliamo)",
  "sorridi": "웃어",
  "spalla": "어깨(zaino in spalla 배낭여행)",
  "spazi": "공간들",
  "spazio": "공간",
  "spero": "나는 바란다",
  "spingere": "밀다",
  "spot": "(광고) 영상",
  "stampi": "너는 인화한다/출력한다",
  "stereotipi": "고정관념들",
  "stereotipo": "고정관념",
  "stesso": "같은/(여기서) 마찬가지",
  "sushi": "스시",
  "tintoria": "드라이클리닝 세탁소",
  "toglie": "제거된다(si toglie 지워진다)",
  "tono": "어조/톤(tono di voce 목소리 크기)",
  "torto": "잘못(avere torto 틀리다)",
  "tradizionali": "전통적인(복수)",
  "tranquilli": "조용한/한적한(복수)",
  "troppa": "너무 많은(여)",
  "turismo": "관광(turismo sostenibile 지속가능 관광)",
  "turistici": "관광의(복수, posti turistici 관광지)",
  "uguali": "같은/똑같은(복수)",
  "universitaria": "대학의(여)",
  "università": "대학",
  "utili": "유용한(복수)",
  "vede": "본다(si vede 보인다)",
  "vegana": "비건의(여)",
  "vegetariano": "채식주의자/채식의",
  "vere": "진짜의(여복)",
  "veri": "진짜의(복수)",
  "voce": "목소리(ad alta voce 큰 소리로)",
  "voli": "항공편들",
  "volo": "비행/항공편(al volo 후딱)",
  "zaino": "배낭",
  "accessorio": "액세서리",
  "affermazione": "주장/진술",
  "alimentare": "식품의/음식의",
  "anziano": "노인",
  "apprendimento": "학습",
  "apprezzare": "감사하다/소중히 여기다",
  "aquila": "독수리",
  "assistenza": "돌봄/지원",
  "autonomia": "자율성",
  "basata": "기반의",
  "bocciare": "낙제시키다",
  "branco": "무리",
  "capire": "이해하다",
  "casa di riposo": "요양원",
  "causa": "원인/때문에",
  "cercare": "찾다/노력하다",
  "certificato": "수료증/자격증",
  "chirurgia": "수술",
  "cinematografico": "영화의",
  "concentrazione": "집중력",
  "concetto": "개념",
  "consapevolmente": "의식적으로",
  "consigliare": "추천하다",
  "contatti": "연락",
  "curativa": "치료의",
  "dedicare": "바치다/할애하다",
  "denaro": "돈",
  "dialogo": "대화",
  "disponibilità": "이용 가능함",
  "domenicale": "일요일의",
  "donare": "기부하다",
  "doppiaggio": "더빙",
  "durare": "지속되다",
  "ecologica": "생태적",
  "educative": "교육적",
  "energia": "에너지",
  "energia rinnovabile": "재생에너지",
  "episodi": "에피소드들",
  "esaurito": "매진된",
  "extra": "추가의",
  "farmaco": "약",
  "fondamentale": "근본적인/중요한",
  "generazione": "세대",
  "gestione": "관리",
  "giocare": "놀다/게임하다",
  "gioia": "기쁨",
  "gioie": "기쁨들",
  "godersi": "즐기다/누리다",
  "gratitudine": "감사",
  "gratuita": "무료의",
  "guerriero": "전사",
  "ibrido": "하이브리드",
  "impronta": "발자국/흔적",
  "impronta ecologica": "탄소발자국",
  "investire": "투자하다",
  "istinto": "본능",
  "istruzione": "교육",
  "laser": "레이저",
  "lenti": "렌즈",
  "livello": "레벨/수준",
  "lotteria": "복권",
  "mammone": "마마보이",
  "mancare": "그립다/모자라다",
  "matematica": "수학",
  "merito": "실적/능력",
  "modello": "모델/방식",
  "montatura": "안경테",
  "nonostante": "~에도 불구하고",
  "occhiali": "안경",
  "occuparsi": "담당하다/돌보다",
  "oculista": "안과 의사",
  "pensione": "연금/은퇴",
  "personaggio": "캐릭터/등장인물",
  "piattaforma": "플랫폼",
  "popcorn": "팝콘",
  "preventiva": "예방의",
  "privata": "민간의/사적인",
  "prodotto": "제품",
  "produttività": "생산성",
  "pubblica": "공공의",
  "radici": "뿌리",
  "recupero": "보충/회복",
  "remoto": "원격의",
  "riflessivo": "재귀의",
  "rilassano": "긴장을 풀다",
  "rinnovabile": "재생 가능한",
  "riunirsi": "다시 만나다",
  "sanità": "공중보건/의료",
  "scolastica": "학교의",
  "segreti": "비결/비밀",
  "selvaggio": "야생의",
  "smart working": "재택근무",
  "smettere": "그만두다/멈추다",
  "somma": "합계/금액",
  "sorso": "한 모금",
  "sostenibilità": "지속가능성",
  "sostituire": "대체하다",
  "spreco": "낭비",
  "streaming": "스트리밍",
  "televisiva": "TV의/텔레비전의",
  "vantaggi": "장점들",
  "videochiamare": "화상통화하다",
  "videogiochi": "비디오게임",
  "videogioco": "비디오게임",
  "vincere": "이기다/당첨되다",
  "vincite": "당첨금/상금",
  "violenza": "폭력",
  "vista": "시력/시야",
  "zoo": "동물원",
  "abbonamento": "정기권",
  "adulti": "어른들",
  "allenarsi": "운동하다/훈련하다",
  "allergia": "알레르기",
  "allergico": "알레르기가 있는",
  "allergie": "알레르기들",
  "amicizie": "우정들",
  "appassionato": "열정적인/팬",
  "arbitro": "심판",
  "artigianato": "장인 정신/수공예",
  "avvolgere": "포장하다",
  "aziendale": "회사의/기업의",
  "brindare": "건배하다",
  "ciecamente": "맹목적으로",
  "coinvolgere": "참여시키다",
  "compenso": "보상/대신",
  "competenza": "능력/역량",
  "confidarsi": "속마음을 털어놓다",
  "conoscenza": "지인/아는 사이",
  "diapositive": "슬라이드",
  "diario": "일기",
  "digitale": "디지털의",
  "educatamente": "정중하게",
  "eleganza": "우아함",
  "energie": "에너지들",
  "esercizio": "운동/연습",
  "eventi": "행사들",
  "evento": "행사",
  "fidarsi": "신뢰하다",
  "fioraio": "꽃집",
  "fiore": "꽃",
  "fioreria": "꽃가게",
  "fiori": "꽃들",
  "fisico": "신체의/물리적",
  "flessibile": "유연한",
  "fontana": "분수",
  "fortuna": "운/행운",
  "giardino": "정원",
  "girasole": "해바라기",
  "girasoli": "해바라기들",
  "grato": "감사한",
  "guadagnare": "벌다/돈을 벌다",
  "impatto": "영향/충격",
  "impegno": "약속/선약",
  "indebolito": "약해진",
  "indipendenti": "독립적인",
  "iscrivermi": "등록하다(재귀)",
  "lunedì": "월요일",
  "lusso": "명품/사치",
  "mazzo": "다발/꽃다발",
  "mensile": "월간의",
  "meteo": "날씨/기상",
  "meteorologica": "기상의",
  "motivato": "의욕 있는",
  "nazionale": "국가의/국립의",
  "nuvoloso": "흐린",
  "occasioni": "경우/행사",
  "oratore": "연설자/발표자",
  "ormai": "이제는/이미",
  "osservare": "관찰하다",
  "panchina": "벤치",
  "parchi": "공원들",
  "partecipato": "참여한",
  "passione": "열정",
  "paura": "두려움/공포",
  "penicillina": "페니실린",
  "personal": "개인의",
  "piovuto": "비가 온",
  "previsioni": "예보/예측",
  "purtroppo": "아쉽게도/유감스럽게도",
  "raccontare": "이야기하다",
  "recensione": "리뷰/후기",
  "recensioni": "리뷰들",
  "regioni": "지역들",
  "regolarmente": "규칙적으로",
  "religione": "종교",
  "rete": "네트워크/네트",
  "richiesta": "요청/부탁",
  "riconcili": "화해하다",
  "riscaldamento": "준비운동/난방",
  "rosa": "장미/분홍색",
  "rose": "장미들",
  "sciroppo": "시럽",
  "scudetto": "세리에A 우승",
  "sfilata": "패션쇼/행렬",
  "sicuro": "확실한",
  "sintesi": "요약",
  "socializzare": "사교하다",
  "spedizione": "배송/발송",
  "sportiva": "스포츠의",
  "stilista": "디자이너/스타일리스트",
  "supportarsi": "서로 지지하다",
  "temporale": "뇌우/폭풍",
  "tenere": "소중히 여기다",
  "tifare": "응원하다",
  "tifoso": "팬/서포터",
  "turno": "교대/근무 시간",
  "umido": "습한",
  "verde": "녹색의/녹지",
  "voglia": "욕구/욕망",
  "abbassare": "낮추다",
  "accoglienza": "환대/수용",
  "addormentarsi": "잠들다",
  "affascinante": "매력적인",
  "algoritmo": "알고리즘",
  "alta velocità": "고속철도",
  "alternativa": "대안",
  "ammirare": "존경하다/감탄하다",
  "ascoltare": "듣다",
  "autentico": "진짜의/진정성 있는",
  "automatizzare": "자동화하다",
  "autostima": "자존감",
  "benessere mentale": "정신 건강",
  "capolavoro": "걸작",
  "chatbot": "챗봇",
  "cittadino": "시민",
  "confrontarsi": "비교하다",
  "creator": "크리에이터",
  "culturale": "문화의",
  "dati": "데이터",
  "dedizione": "헌신",
  "democrazia": "민주주의",
  "desiderio": "욕구/바람",
  "detox": "디톡스",
  "dibattuto": "논쟁적인",
  "difetti": "단점들",
  "disuguaglianza": "불평등",
  "divario": "격차",
  "economica": "경제적인",
  "effetto": "효과",
  "etico": "윤리적인",
  "farfalla": "나비",
  "fenomeno": "현상",
  "frecciarossa": "프레챠로사(고속철)",
  "globale": "세계적인",
  "immergersi": "몰입하다",
  "immigrato": "이민자",
  "immigrazione": "이민",
  "incubo": "악몽",
  "influencer": "인플루언서",
  "integrazione": "통합",
  "investirei": "투자할 것이다",
  "leader": "지도자",
  "macchina del tempo": "타임머신",
  "memorabile": "기억에 남는",
  "mentale": "정신적인",
  "migliorerebbe": "나아질 것이다",
  "multiculturale": "다문화의",
  "nord": "북부",
  "origini": "출신/기원",
  "overtourism": "과잉 관광",
  "pianeta": "행성/지구",
  "politica": "정치/정책",
  "presidente": "대통령/의장",
  "prima classe": "1등석",
  "priorità": "우선순위",
  "procrastinare": "미루다",
  "proposta di legge": "법안",
  "puntata": "회차/편",
  "qualità della vita": "삶의 질",
  "raccomandazione": "추천/권고",
  "reddito": "소득",
  "redistribuzione": "재분배",
  "riposante": "편안한/푹 쉬게 하는",
  "ritmo": "리듬/박자",
  "ritmo di vita": "생활 리듬",
  "scoprire": "발견하다",
  "scrittore": "작가",
  "servizi": "서비스/편의시설",
  "sonno": "수면/잠",
  "sponsorizzato": "협찬된",
  "spopolamento": "인구 감소",
  "stanotte": "오늘 밤",
  "sud": "남부",
  "svegliarsi": "깨다/일어나다",
  "tema": "주제",
  "testimone": "목격자/증인",
  "traduttore": "번역기",
  "turismo lento": "슬로우 트래블",
  "vegano": "비건",
  "velocità": "속도",
  "voto": "투표/표",
  "agosto": "8월",
  "andare avanti": "앞으로 나아가다",
  "annuale": "연간의",
  "burnout": "번아웃",
  "campanilismo": "지역주의",
  "capirsi": "서로 이해하다",
  "carbonara": "카르보나라",
  "carriera": "커리어/경력",
  "cattolicesimo": "가톨릭교",
  "chiesa": "교회/성당",
  "chiese": "교회들",
  "chiusura": "휴무/마감",
  "compito": "과제/임무",
  "contributo": "기여/공헌",
  "convivialità": "함께 식사하는 즐거움",
  "coordinare": "조율하다",
  "culinaria": "요리의",
  "cuocere": "익히다/요리하다",
  "design": "디자인",
  "dialetto": "방언",
  "digestivo": "식후 소화 음료",
  "esprimersi": "자신을 표현하다",
  "estetica": "미학",
  "ferie": "유급 휴가",
  "ferito": "상처받은",
  "ferragosto": "페라고스토(이탈리아 여름 휴가 최성수기)",
  "frenetica": "바쁜/정신없는",
  "funzionalità": "기능성",
  "gap generazionale": "세대 차이",
  "garanzia": "보증/보장",
  "generazionale": "세대의",
  "gestire": "관리하다",
  "innovazione": "혁신",
  "introverso": "내향적인",
  "laico": "세속적인",
  "lavorativo": "직업의/노동의",
  "leadership": "리더십",
  "liberamente": "자유롭게",
  "logorando": "갉아먹는",
  "made in italy": "메이드 인 이탈리아",
  "orgoglio": "자부심",
  "patrimonio": "문화유산",
  "perdonare": "용서하다",
  "perdono": "용서",
  "pisolino": "낮잠",
  "pomeridiano": "오후의",
  "primo piatto": "첫 번째 코스",
  "rancore": "원한/앙심",
  "realizzarsi": "자아실현하다",
  "regionale": "지역의",
  "ricaricarsi": "재충전하다",
  "riconciliarsi": "화해하다",
  "riconciliazione": "화해",
  "riposo pomeridiano": "오후 휴식",
  "scuse": "사과",
  "sinonimo": "동의어",
  "stabilità": "안정성",
  "stare da solo": "혼자 있다",
  "straordinari": "야근/초과근무",
  "sviluppo": "발전/개발",
  "tacere": "침묵하다/말하지 않다",
  "valori": "가치관들",
  "abbracciare": "안아주다",
  "abbraccio": "포옹",
  "accesso": "접근/이용",
  "adottare": "입양하다",
  "allegato": "첨부파일",
  "ammettere": "인정하다",
  "animale domestico": "반려동물",
  "astronauta": "우주비행사",
  "attraversare": "통과하다/겪다",
  "automazione": "자동화",
  "cambiamento climatico": "기후변화",
  "canile": "개 보호소",
  "colonna sonora": "영화 사운드트랙",
  "condividere": "공유하다",
  "consumo": "소비",
  "costanza": "꾸준함",
  "dedicarsi": "몰두하다/전념하다",
  "disdire": "해지하다/취소하다",
  "disinformazione": "허위정보",
  "emissioni": "배출량",
  "errore": "실수/오류",
  "esclamazione": "감탄사",
  "esplorazione": "탐험",
  "essenziale": "필수적인/본질적인",
  "extraterrestre": "외계의/외계 생명체",
  "fake news": "가짜 뉴스",
  "fonte": "출처/원천",
  "galassia": "은하",
  "gelosia": "질투",
  "geloso": "질투하는",
  "gravità": "중력",
  "immersione": "몰입",
  "inconfondibili": "독보적인",
  "invidia": "시기/부러움",
  "liberarsi": "해방되다",
  "linguistica": "언어의",
  "melodia": "멜로디",
  "minimalismo": "미니멀리즘",
  "motivazione": "동기",
  "navicella": "우주선",
  "orbita": "궤도",
  "ozio": "여가/무위",
  "pensiero critico": "비판적 사고",
  "premiato": "수상한",
  "reddito di base": "기본소득",
  "regista": "영화 감독",
  "ripetizione": "반복",
  "riposarsi": "쉬다",
  "sceneggiatura": "시나리오/각본",
  "scomparire": "사라지다",
  "sfida": "도전/과제",
  "sonora": "음향의",
  "spaziale": "우주의",
  "supporto": "지지/도움",
  "tempo libero": "여가 시간",
  "testo": "가사/텍스트",
  "tradurre": "번역하다",
  "tutela": "보호/수호",
  "veterinario": "수의사",
  "viceversa": "반대도 마찬가지로",
  "acquisto impulsivo": "충동구매",
  "cartaceo": "종이의",
  "coltivare": "재배하다",
  "consumismo": "소비주의",
  "esigenza": "필요/욕구",
  "espressivo": "표현력이 풍부한",
  "fraintendere": "오해하다",
  "gesticolare": "제스처를 쓰다",
  "immaginazione": "상상력",
  "km zero": "로컬 푸드",
  "linguaggio del corpo": "몸짓 언어",
  "orto urbano": "도시 텃밭",
  "realizzare": "실현하다",
  "scortesia": "무례함",
  "sperare": "희망하다",
  "stagionale": "제철의",
  "statua": "동상/조각상",
  "svendita": "세일/할인",
  "tramandare": "전수하다",
  "trasmettere": "전달하다",
};

export interface VocabItem {
  word: string;
  reading: string;
  meaning: string;
}

export function getVocab(texts: string[]): VocabItem[] {
  const seen = new Set<string>();
  const out: VocabItem[] = [];
  for (const text of texts) {
    const matches = text.match(/[A-Za-zÀàÈèÉéÌìÍíÒòÓóÙùÚúA-Za-z]+/g);
    if (!matches) continue;
    for (const raw of matches) {
      const key = raw.toLowerCase();
      if (seen.has(key)) continue;
      seen.add(key);
      const meaning = glossary[key];
      if (!meaning) continue;
      out.push({ word: raw, reading: esToHangul(raw), meaning });
    }
  }
  return out;
}

/** 대화 라인 배열에서 등장 단어를 첫 등장 순서대로 모아 뜻을 붙여 반환합니다. */
export function getDialogueVocab(lines: { text: string }[]): VocabItem[] {
  return getVocab(lines.map((l) => l.text));
}
